port: 8080
folder_url: /minecraft
highlighter: rouge
title: "minecraft diary"
paginate: 3
paginate_path: "page:num"


plugins:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate