port: 8080
folder_url: /minecraft
title: "minecraft diary"
paginate: 3
paginate_path: "page:num"

markdown: kramdown
highlighter: rouge
kramdown:
   input: GFM #Github Flavored Markdown
   hard_wrap: true  
   syntax_highlighter: rouge

plugins:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate